FROM ubuntu:23.04

RUN apt update && apt install -y \
    make \
    gcc \
    libwayland-dev \
    wayland-protocols \
    libcairo-dev \
    libgd-dev

WORKDIR /build
COPY . .

ENV HAVE_WAYLAND=1
RUN cp Makefile.DIST Makefile && make -j && cp xearth /target/
