FROM fedora:40

RUN dnf install -y \
    make \
    gcc \
    wayland-devel \
    wayland-protocols-devel \
    cairo-devel \
    gd-devel

WORKDIR /build
COPY . .

ENV HAVE_WAYLAND=1
RUN cp Makefile.DIST Makefile && make -j \
    && mkdir -p /target && cp xearth /target/
